DxCx/plugin.video.9anime

resources/lib/NineAnimeBrowser.py, resources/lib/ui/embed_extractor.py, resources/lib/ui/test_utils.py, test/test_browser.py
QuickFix for #4 
OpenLoad still not working.
=> 9anime fix

resources/lib/NineAnimeBrowser.py, test/test_browser.py
=> temporary disabled openload

resources/lib/ui/embed_extractor.py, resources/lib/ui/test_utils.py
=> Openload fix

default.py, resources/lib/NineAnimeBrowser.py, test/test_browser.py
=> fix(genre): paging was not handled correctly

resources/lib/NineAnimeBrowser.py
=> fix(genre): pass page conventionaly

resources/lib/NineAnimeBrowser.py
Sources fix will be taken care of as part of #16 
Closes #14
=> Site Browser update

README.md, default.py, resources/lib/NineAnimeBrowser.py, resources/lib/ui/BrowserBase.py, resources/lib/ui/NineAnimeTokenDecoder.py, resources/lib/ui/embed_extractor.py, resources/lib/ui/http.py, resources/lib/ui/test_NineAnimeTokenDecoder.py, resources/lib/ui/test_utils.py, test/test_browser.py
Refactoring of #27 
Closes #27 
Closes #24
=> Add 9Anime token support

README.md
=> Add Firestick instructions

resources/lib/ui/NineAnimeTokenDecoder.py
Thanks one more @githubus11 :)
=> Token line fetch

resources/lib/ui/embed_extractor.py
=> Grabber params

addon.xml
=> chore(addon): change req to python 2.25 to block kodi < 17

resources/lib/ui/control.py, resources/lib/ui/embed_extractor.py
=> Lazy openload

README.md
Closes #44 
@hoppler what do you think?
=> Add Repository to readme.md

resources/lib/ui/control.py, resources/lib/ui/embed_extractor.py, resources/lib/ui/test_utils.py
=> adds support for Mycloud

.gitattributes
this way zip file should not contain uneeded files.
=> add gitattribute file to ignore exports

addon.xml, default.py, resources/language/English/strings.xml, resources/language/Hebrew/strings.xml, resources/lib/NineAnimeBrowser.py, test/test_browser.py
=> feat(filters): add recent subbed/dubbed support

README.md, default.py, resources/language/English/strings.xml, resources/language/Hebrew/strings.xml, resources/lib/NineAnimeBrowser.py, test/test_browser.py
Attempt at completing #76, but I can't get it to work. I would appreciate any kind of help.
The links I am using are https://9anime.to/filter?sort=views%3Adesc&language=dubbed and https://9anime.to/filter?sort=views%3Adesc&language=subbed. I believe the problem is in either default.py or NineAnimeBrowser.py shown below.
```
@route('popular_subbed')
def POPSUBBED(payload):
return control.draw_items(_BROWSER.get_popular_subbed())
@route('popular_subbed/*')
def POPSUBBED_PAGES(payload):
return control.draw_items(_BROWSER.get_popular_subbed(int(payload)))
@route('popular_dubbed')
def POPDUBBED(payload):
return control.draw_items(_BROWSER.get_popular_dubbed())
@route('popular_dubbed/*')
def POPDUBBED_PAGES(payload):
return control.draw_items(_BROWSER.get_popular_dubbed(int(payload)))
```
``` …
```
=> Popular subbed/dubbed support

default.py, resources/lib/ui/control.py
Closes #74 
Thanks @hoppler ! :D always happy to learn more things
do you know how do i set more metadata on the items themselves? maybe i'll scrap them as well if it won't hurt perforamnce.
=> Set content

default.py, resources/lib/ui/SourcesList.py, resources/lib/ui/utils.py, resources/settings.xml
Closes #62 
Based on @justin89h pr
=> Added settings for autoplay, resolution sorting, and episode sorting

resources/lib/NineAnimeBrowser.py
=> Change domain back to 9anime.to

default.py, resources/lib/ui/SourcesList.py, resources/lib/ui/utils.py, resources/settings.xml
- Based on #108 
- Refactored to allow preferred resolution as suggested by @hoppler in #104.
Thanks @hoppler ! 👍 
Closes #108
=> Replaced Resolution Sorting Alogirthem

resources/language/English/strings.xml
Changed `eliable` to `eligible`.
=> Corrected Spelling

README.md, default.py, resources/settings.xml
Closes #130
Replaces #132 #133
Thanks @miasmaejuices!
=> chore(Server-Gx): add G1/G2 sources

addon.xml, changelog.txt
=> chore(addon): update to version 0.0.23

resources/lib/NineAnimeBrowser.py
9anime has changed the base url and hopefully this will fix the current issue where nothing can be played
=> Change the base url to 9anime.is

resources/lib/ui/control.py, resources/lib/ui/embed_extractor.py, resources/lib/ui/http.py
=> Support Cookie for F2 Sources

addon.xml, changelog.txt
=> chore(addon): update to version 0.0.40

addon.xml, changelog.txt
=> chore(addon): update to version 0.0.41

default.py, resources/lib/NineAnimeBrowser.py, resources/settings.xml
Hey guys,
Adding the search history, with the possibility to enable/disable it from settings.
ref #185
Thanks,
=> Adding search history
